version: '2'
services: 
    web:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - postgres
    postgres:
        build: .
        dockerfile: Dockerfile-postgres
        environment: 
            POSTGRES_DB: db_welbex
            POSTGRES_PASSWORD: postgres 
        restart: always

