FROM postgres
RUN mkdir /home/db/
COPY app/db_welbex.dump /home/db/db_welbex.dump
ADD app/init.sql /docker-entrypoint-initdb.d/
WORKDIR /home/db
CMD ["pg_restore", "-U postgres", "-h localhost", "-w", "db_welbex", "db_welbex.dump" ]