version: '2'
services: 
    web:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - postgres
    postgres:
        image: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: postgres 
